"""Update Order model to support guest orders

Revision ID: 2ebdf7a650cd
Revises: 82d9ea72754b
Create Date: 2025-03-19 15:53:56.343112

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2ebdf7a650cd'
down_revision = '82d9ea72754b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('guest_identifier', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('email', sa.String(length=128), nullable=False))
        batch_op.add_column(sa.Column('shipping_address', sa.String(length=256), nullable=False))
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.drop_column('shipping_address')
        batch_op.drop_column('email')
        batch_op.drop_column('guest_identifier')

    # ### end Alembic commands ###
