"""Update Order model to support customer name

Revision ID: 45ba8beb1122
Revises: 2ebdf7a650cd
Create Date: 2025-03-19 16:10:36.338024

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45ba8beb1122'
down_revision = '2ebdf7a650cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer_name', sa.String(length=128), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('customer_name')

    # ### end Alembic commands ###
