"""Add merchant_reference and pesapal_tracking_id to orders

Revision ID: a1b2c3d4e5f6
Revises: 5c05eaab1928
Create Date: 2025-01-27 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1b2c3d4e5f6'
down_revision = '5c05eaab1928'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('merchant_reference', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('pesapal_tracking_id', sa.String(length=128), nullable=True))
        batch_op.create_index('ix_orders_merchant_reference', ['merchant_reference'], unique=True)
        batch_op.create_index('ix_orders_pesapal_tracking_id', ['pesapal_tracking_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index('ix_orders_pesapal_tracking_id')
        batch_op.drop_index('ix_orders_merchant_reference')
        batch_op.drop_column('pesapal_tracking_id')
        batch_op.drop_column('merchant_reference')

    # ### end Alembic commands ###
